global:
    scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s

    static_configs:
        - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 20s

    static_configs:
        - targets: ['192.168.1.1:8080']

